--- #YAML:1.0
name:               optimizer
version:            0.06_06
abstract:           Write your own Perl optimizer, in Perl
author:
    - Simon Cozens, Arthur Bergman, Reini Urban
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Generate:  1.26
    DynaLoader:   0
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rurban/optimizer
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
