--- #YAML:1.0
name:               optimizer
version:            0.06_03
abstract:           Write your own Perl optimizer, in Perl
author:
    - Simon Cozens, Arthur Bergman, Reini Urban
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Generate:  0
    DynaLoader:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.5601
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
