---
abstract: 'Write your own Perl optimizer, in Perl'
author:
  - 'Simon Cozens, Artur Bergman, Reini Urban'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: optimizer
no_index:
  directory:
    - t
    - inc
requires:
  B::Generate: 1.26
  DynaLoader: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rurban/optimizer
version: 0.07
